feat(e2e-test): Set settings to run firebase emulator on github actions
ecomplus/cloud-commerce pull request #156
Opened 2023-05-04 21:10 UTC by wisley7l

Referente ao #151 

Apenas um primeiro teste, batendo list_payments
As config, tais como versão do node, pnpm  é firebase-tools escolhi as mesmas que executam na minha maquina.

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          node-version: 18.3.0
```suggestion
          node-version: 18
```

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          npx kill-port 4000 9099 5001 8080 5000 8085 9199 4400 4500 && npm run serve &
```suggestion
          npm run serve &
```

Acho que não tem como essas portas estarem ocupadas no container do workflow não (na sua máquina sim..)

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          sleep 50
Eita precisa desses 50s mesmo ? 😆

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +        run: git clone https://github.com/ecomplus/store
Problema é aqui você só vai testar a versão commitada no https://github.com/ecomplus/store , por sua vez com a versão já publicada dos pacotes, na verdade a gente precisa do source atual com checkout desse repo aqui mesmo com o store como submódulo...

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +        run: git clone https://github.com/ecomplus/store
https://github.com/actions/checkout

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
Acho que isso aqui não gasta não, gasta?

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +        run: git clone https://github.com/ecomplus/store
`submodules` é uma opção do checkout, talvez dê pra especificar só um submódulo inclusive...

2023-05-05 00:22 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          ECOM_API_KEY: ${{ secrets.ECOM_API_KEY }}
👀 
> pra eu lembrar de adicionar os secrets

2023-05-05 00:26 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +      - "packages/apps/**"
Por que só vai rodar em pull request e por que só nos apps ?
Também depende do `packages/modules` e esse por sua vez depende de outras paradas ainda...
Talvez seja mais fácil ouvir todos os pacotes adicionando algumas exceções (storefront, passport, mais?)

2023-05-05 00:26 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +      - "packages/apps/**"
E acho que tem que rodar no push em main também, com possibilidade de ser skipado com `[skip ci]`: https://github.com/ecomplus/storefront-starter/blob/master/.github/workflows/build-and-deploy.yml#LL23C40-L23C40

2023-05-13 00:50 UTC, leomp12 commented on packages/modules/tests/index.test.mjs
> +
```suggestion
```

2023-05-13 00:50 UTC, leomp12 commented on packages/modules/tests/index.test.mjs
> +
```suggestion
```

2023-05-13 00:50 UTC, leomp12 commented on packages/modules/tests/index.test.mjs
> +// const apiUrl = 'https://dev.ecomplus.io/v2';
Ué de onde veio isso? haha

2023-05-13 00:50 UTC, leomp12 commented on packages/modules/tests/index.test.mjs
> +// const apiUrl = 'https://dev.ecomplus.io/v2';
```suggestion
```

2023-05-14 20:28 UTC, leomp12 requested changes

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          version: 7
```suggestion
          version: 8
```

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          npx firebase --project=test emulators:start --only functions,hosting,firestore &
Precisa emular Hosting aqui mesmo? E tem como evitar emular todas as funções?
No deploy tem como setar a opção `--only functions:$DEPLOY_CODEBASE`

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          npx firebase --project=test emulators:start --only functions,hosting,firestore &
Ideal inclusive era evitar emular o Firestore também, talvez em algum momento testes de apps precisem dele mas a priori começa evitando...

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          npx firebase --project=test emulators:start --only functions,hosting,firestore &
A intenção sempre é que o teste seja executado com o mínimo de tempo necessário né

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          cache-name: packages-build-${{ steps.get-version.outputs.VERSION }}
Mas isso aqui faz sentido não, faz?
Você tá salvando o cache das dependências em função da versão de cada pacote, é isso? Com isso o teste rodaria sem atualizar as dependências enquanto não houver um release novo, ou seja, não testaria atualização de dependências...

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          cache-name: packages-build-${{ steps.get-version.outputs.VERSION }}
Tem que haver cache das dependências mesmo, mas baseado só no `pnpm-lock.yaml` (lock file do monorepo), não?

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +            pnpm install --no-frozen-lockfile
`--no-frozen-lockfile` ?

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +            pnpm build
Não tem porque buildar todos os pacotes, tem?

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +              pnpm build
Uai mas você já tinha compilado tudo do root...

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +              npm link
Isso definitivamente não deveria ser necessário 😄

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +            fi
Eu acho que faz mais sentido separar os testes do SSR na verdade, não vai dar pra ser só com o test runner do Node inclusive

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +              npm link
Pra isso mesmo serve o workspace do pnpm

2023-05-14 20:28 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +
Tinha que ter sempre um `pnpm i` no root aqui na verdade (eventualmente skipado pelo cache...)

2023-05-14 20:34 UTC, leomp12 requested changes
Sobre esse setup com vários `npm i` e `npm link` dá uma olhada aqui https://github.com/ecomplus/cloud-commerce/blob/main/CONTRIBUTING.md#prepare-your-environment
O necessário deveria ser só isso na verdade (só um `pnpm i` no root), nesse caso sem o clone do submodule inclusive porque ele já vem no checkout...

2023-05-14 20:34 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          npx firebase --project=test emulators:start --only functions,hosting,firestore &
E esse `--project=test`?

2023-05-14 20:34 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          npm run build
Não é pra ter esse `npm i` também não, `pnpm i` no root também instala as dependências do `store/` e `store/functions/*`...

2023-05-14 21:17 UTC, leomp12 commented
Na verdade o `pnpm i` (root) deve ser um step logo após o step de cache, sempre será executado mas eventualmente é mais rápido porque pega do cache.
Daí o step seguinte é `pnpm build` (também no root) pra todos os pacotes mesmo, mas pra ele também precisamos de cache (pra isso serve o https://github.com/ecomplus/cloud-commerce/blob/main/turbo.json) pra tentar agilizar (evitar compilar os pacotes inalterados), idealmente o cache seria com artifacts do GH Actions mesmo (como acontece com dependências) mas se for inviável podemos fazer com [cloud do próprio Turborepo](https://turbo.build/repo/docs/core-concepts/remote-caching) (a.k.a. Vercel).

2023-05-14 21:39 UTC, leomp12 commented
Se os `npm link` forem por causa do `firebase-tools` , talvez instalando ele com pnpm também? Talvez em dev dep do monorepo (root) mesmo?

2023-05-16 20:42 UTC, wisley7l commented on packages/modules/tests/index.test.mjs
> +// const apiUrl = 'https://dev.ecomplus.io/v2';
Esse foi um incremento nessa PR, para executar os testes usando a lib nativa do node18

2023-05-16 21:07 UTC, wisley7l commented
O motivo do `npm link` é pq quando eu realiza alguma ateração não era aplicado ao teste, porém com as revisões que fiz agora notei que a forma que eu executava os testes na minha máquina que não estavam corretas. 

Ja o uso `--only functions:$DEPLOY_CODEBASE`, no emulador ainda não parece ser possivél. 
encontrei esse issue aqui sobre algo parecido https://github.com/firebase/firebase-tools/issues/4878, pelo que entedi aqui a solução temporária foi criar outro arquivo `firebase.json` secundario para executar as funções necessárias nos testes.

2023-05-16 23:21 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          key: ${{ runner.os }}-pnpm-build-${{ hashFiles('**/pnpm-lock.yaml') }}
A key pro cache do build não tem nada a ver com o lock file das dependências na real 😄
E o path também não é esse aí não, é alguma pasta do turborepo

2023-05-16 23:21 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          key: ${{ runner.os }}-pnpm-build-${{ hashFiles('**/pnpm-lock.yaml') }}
Vou remover daqui por enquanto mas temos que adicionar depois...

2023-05-16 23:21 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +            ${{ runner.os }}-pnpm-build-
```suggestion
```

2023-05-16 23:25 UTC, leomp12 requested changes

2023-05-16 23:25 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          pnpm install
```suggestion
        run: pnpm fix-install
```

2023-05-16 23:25 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          pnpm install
https://github.com/ecomplus/cloud-commerce/blob/main/package.json#L14

2023-05-16 23:25 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          pnpm install
Inclusive também é usado no release https://github.com/ecomplus/cloud-commerce/blob/main/scripts/release.mjs#L94

2023-05-16 23:25 UTC, leomp12 commented on .github/workflows/e2e-tests.yml
> +          pnpm install
Deve resolver o erro aí https://github.com/ecomplus/cloud-commerce/actions/runs/4997591598/jobs/8952108818 e outros que dão quando tem submodules com outras lojas..

2023-05-17 01:23 UTC, leomp12 approved these changes
valeu @wisley7l 👍🏾

2023-05-17 20:19 UTC, leomp12 approved these changes
> Foi bom pra descobrir isso aí também https://github.com/ecomplus/cloud-commerce/pull/156/commits/20d9d21c3d36f450db562122a55d74295a05b006

2023-05-17 20:20 UTC, merged