chore(test-app-emails): add test in emails app and improvements to the test-base for test setup
ecomplus/cloud-commerce pull request #398
Opened 2024-06-06 21:20 UTC by wisley7l

2024-06-07 17:56 UTC, leomp12 requested changes
Testes e2e só podem ser executados no working directory de alguma loja (via de regra a demo), isso significa que `./functions/**` já vai existir, tal qual o `content/settings.json`, criar esses arquivos durante o teste é desnecessário e substituí-los é de fato um erro na verdade, seu teste pode sujar os arquivos de produção.
Em contrapartida, testes unitários não deveriam necessitar de toda a estrutura de arquivos idêntica, não emularia o Firebase, etc...
O teste que você implementa aqui pro app de e-mails me parece uma mistura dos dois, ficou meio nem lá nem cá.

Acho que esse teste deveria ser executado em e2e, com emulação do Firebase pra todas as funções, e essa função `setupForTests` definitivamente não deveria existir, pelo menos não fazendo o que está proposto aqui.

2024-06-07 17:56 UTC, leomp12 commented on packages/apps/emails/tsconfig.test.json
Esse arquivo não tem utilidade, de qualquer forma tem que especificar um config file diferente com `tsc -p` então poderia apontar direto pro `../../../tsconfig.test.json`

2024-06-07 17:56 UTC, leomp12 commented on packages/apps/emails/test.env
A priori poderia usar o `.env` normal, não?
De toda forma deveria ser [`.env.test`](https://github.com/ecomplus/cloud-commerce/blob/main/.gitignore#L18C1-L18C10) e certamente esse arquivo não pode ser comitado, considerando as variáveis que ele inclui aqui (vez ou outro um token indevido seria publicado).
As variáveis de ambiente se repetem e ter que duplicar não parece vantajoso, ideal seria testar se existe um `.env.test`, caso contrário usa o `.env`.

2024-06-07 17:56 UTC, leomp12 commented on packages/test-base/src/index.ts
> +export * from 'vitest';
Isso aqui não faz sentido 😄

2024-06-07 17:56 UTC, leomp12 commented on packages/test-base/package.json
> +    "vitest": "^1.6.0"
`vitest` não é usado programaticamente em nenhum arquivo desse codebase, não deveria estar nas dependências aqui não...

2024-06-07 17:56 UTC, leomp12 commented on packages/test-base/src/prepare-tests.ts
> +  ecomUtils,
Por que tá reexportando isso?

2024-06-07 17:56 UTC, leomp12 commented on packages/test-base/src/prepare-tests.ts
> +  ecomUtils,
A lib que precisar deveria importar dos respectivos pacotes, não daqui na verdade

2024-06-07 17:56 UTC, leomp12 commented on packages/test-base/package.json
> +    "vitest": "^1.6.0"
Mesma coisa pro `@ecomplus/utils` aliás

2024-06-07 17:56 UTC, leomp12 commented on packages/test-base/src/prepare-tests.ts
> +};
Mas daí toda vez que for executar testes você edita o `.gitignore` e sobescreve o `content/settings.json`?
Não é boa ideia não em...

2024-06-13 20:58 UTC, wisley7l commented
Posso estar engando, mas os teste que criamos para os apps até o momento são executados dentro do dir do cloudcommerce. 
Durante a semana tentei fazer as correções e melhorias nessa PR, mas hoje acredito ter encontrado uma outra solução para teste em funções com `pub/sub` no qual estava tentando executar nessa PR. 

essa [outra forma de executar teste com pub/sub](https://medium.com/@granttimmerman/test-pub-sub-with-the-functions-framework-and-pub-sub-emulator-a2dc39196603), fiz uns testes locais aqui me parece ok, porém vi que ele meio que sobre outro servidor(isso em testes) para receber as requisições para o pub/sub, agora o que preciso verifica se seria possivel subir todas funcções que usam pubsub e atraves desse serve testar as funções de forma individual.

O que notei é que caso a função retorne com sucesso ele responde 204 em caso de alguma falha ( das testas até o momento) responde 500, também me falta verificar quando a função pubsub quebra ou tenha alguma falha interna. 

Mas para essa outra solução irei abrir novo PR

2024-06-17 17:16 UTC, leomp12 commented
> Posso estar engando, mas os teste que criamos para os apps até o momento são executados dentro do dir do cloudcommerce.

Não no diretório cloudcommerce, testes e2e devem ser executados no diretório de loja, por padrão na demo em `/store`. Se os testes e2e atuais não estão sendo executados dessa forma eles estão errados 🙃 
Não faz sentido executar testes de integração sem emular a loja inteira.
Testes em cada pacote devem ser apenas testes unitários.

2024-06-17 17:26 UTC, leomp12 commented on packages/apps/emails/tsconfig.test.json
Esse arquivo não deve existir

2024-06-17 17:28 UTC, leomp12 commented
E não tem porque não usar vitest nesse monorepo, já é uma dependência de qualquer maneira e parece ser claramente melhor que o test runner nativo do Node.

2024-06-28 19:53 UTC, wisley7l commented
Fechando PR,
PR muito extensa e provavelmente não será utilizada para merge.
Salvar os reviews para as próximas PRs

2024-07-05 12:52 UTC, closed without merging