chore(cli): Create and prepare store to tests
ecomplus/cloud-commerce pull request #406
Opened 2024-06-28 19:45 UTC by wisley7l

2024-06-28 19:51 UTC, wisley7l commented
A principio a ideia era talvez centralizar os teste para loja no pacote `test-base`, mas tive alguns erros aqui, acredito que possa ser que o pacote é um pacote privado e quando executado na loja vai ocorrer erros e não sei se ficaria legal ter outro comando cli apenas para testes. 

(Criei um fluxo para ter mais ideia de um teste mais completo, desde a criação do pedido até a verificação da notificação de recebimento do cliente)[https://www.mindmeister.com/app/map/3339555195?t=dFegi6OdxL]

2024-07-04 21:12 UTC, leomp12 requested changes
Mano sinceramente eu não entendi nem a motivação dessa PR, não sei o que você quis fazer aqui...
O CLI já tem comandos (acho que `serve`) que emulam as Functions to Firebase, se for necessário edite algo nesse comando e emulação, obviamente eles já são pra testes.
Fora isso as funções que você criou pra checar pastas não me parecem ser necessárias e se estão sendo não deveriam.
Observe os npm scripts já adicionados em https://github.com/ecomplus/store/blob/main/package.json#L9-L11

2024-07-04 21:12 UTC, leomp12 commented on packages/cli/package.json
> +    "vitest": "^1.6.0"
`vitest` só precisa estar em dev deps do monorepo (já está)

2024-07-04 21:12 UTC, leomp12 commented on packages/cli/package.json
> +    "vitest": "^1.6.0"
A não ser que **precise** estar em dependência mesmo (não dev dep), o que também não é o caso aqui

2024-07-04 21:12 UTC, leomp12 commented on packages/cli/tests/store.test.ts
Não faz sentido testes de outros pacotes estarem no codebase do pacote `cli`

2024-07-04 21:12 UTC, leomp12 commented on packages/cli/src/prepare-test-store.ts
Não entendo porque isso seria necessário

2024-07-04 21:12 UTC, leomp12 commented on packages/cli/tests/store.test.ts
Além disso esses mesmos testes já não existem no respectivo pacote (`modules`)?

2024-07-04 21:19 UTC, leomp12 commented
> a ideia era talvez centralizar os teste

Má ideia, cada teste em seu pacote (seu codebase).

> pacote é um pacote privado e quando executado na loja vai ocorrer erros e não sei se ficaria legal ter outro comando cli apenas para testes

Qual pacote é privado? O monorepo está devidamente instanciado na execução dos testes?

O CLI só precisa de comandos que emulem a loja, se não me engano eles já existem, com a loja sendo emulada os scripts `test:e2e` de todos os pacotes (que tiverem) devem ser executados.

Portanto o workflow de testes e2e instala corretamente o monorepo (sempre, qualquer CI), inicia a emulação da loja toda em localhost  e roda `turbo run test:e2e --filter='!./ecomplus-stores/**'`.

2024-07-04 21:32 UTC, leomp12 commented
No meu terminal com o monorepo preparado (obviamente) e logado no `firebase-tools`:

```bash
cd store
pnpm serve
```

Funciona perfeitamente emulando todas as Functions, Hosting, Firestore...
Ou seja, o CLI tá fazendo o seu papel aí também em pra ambiente de teste, não é necessário mover pastas e etc etc, mesmo porque fazer isso seria maquiar o teste, o ambiente tem que estar o mais próximo possível de produção.

No meu terminal o que falta pra executar um teste e2e de um módulo de pagamento, portanto, é o próprio script de teste nesse módulo de pagamento, que siga o fluxo que você criou consumindo (em localhost) as funções que já estão emuladas. Nesse caso não há o que mexer no pacote do `cli`, falta escrever os testes no pacote do respectivo app.

Em ambiente de CI/CD (GitHub Actions) possivelmente falte mais coisas, talvez tenha que preparar o `firebase-tools` env em `store/functions/.env` , mas nada disso tem relação com o pacote `cli` também, especialmente o .env que deve usar Secrets do repositório, provável que ambos sejam definidos diretamente no workflow do GH Actions.

2024-07-04 21:49 UTC, wisley7l commented
Minha confusão está sendo então porque no outro PR mencionamos sobre os testes. 
> > Posso estar engando, mas os teste que criamos para os apps até o momento são executados dentro do dir do cloudcommerce.

> Não no diretório cloudcommerce, testes e2e devem ser executados no diretório de loja, por padrão na demo em /store. Se os testes e2e atuais não estão sendo executados dessa forma eles estão errados 🙃
Não faz sentido executar testes de integração sem emular a loja inteira.
Testes em cada pacote devem ser apenas testes unitários.

https://github.com/ecomplus/cloud-commerce/pull/398#issuecomment-2173932624

Então minha ideia inicial nesse PR aqui era que os testes fossem executados dentro do diretorio da loja.

2024-07-04 21:57 UTC, leomp12 commented
Mas se estamos emulando a loja em `store`, onde estariam sendo executados os testes?
A sessão do seu shell vai estar justamente no diretório da loja, único lugar inclusive onde estarão as variáveis de ambiente, assim como em produção, não nas pastas dos pacotes.

2024-07-04 22:05 UTC, leomp12 commented
> testes e2e devem ser executados no diretório de loja

Executados, não escritos.
Na outra PR você copiava env pro diretório de pacote de app, criava pastas tentando mascarar os diretórios da loja, tentava mockar a ação de outros pacotes sem emular... Então o que comentei é que o certo era não fazer nada disso, em vez disso naturalmente apenas emular a loja inteira, no diretório dela mesmo pra não ter que sair copiando as coisas pra lá e pra cá.
Sugeri a mesma coisa novamente:
```bash
cd store
pnpm serve
```

2024-07-04 22:09 UTC, leomp12 commented
Mas o comando _execute os testes_ não precisa necessariamente partir do diretório da loja, não há razão pra exigir isso, na prática tanto faz, mas partindo do root do monorepo vai ser mais simples executar os testes de todos os pacotes em sua versão atual não necessariamente publicada, seja com `turbo` ou `pnpm` workspaces diretamente.
O que deve acontecer no diretório da loja é a emulação do servidor inteiro (isso faz parte dos testes inclusive), estando assim mais próximo do ambiente em produção (e2e) e evitando todas as gambiarras adicionais com essas pastas e .env.

2024-07-04 22:13 UTC, leomp12 commented
Ou seja, não quero que você tente inventar um diretório parecido com o /store em um diretório de algum outro pacote, menos ainda quero que copie os arquivos de config e env pra além do que já é feito em produção, fora isso se você executa o comando `comece a testar` da pasta /store, da sua home (~/), de /tmp ou de qualquer outro lugar tanto faz haha
O ponto é que `comece a testar` não deve fazer gambiarras desnecessárias e até indevidas, pra isso você vai precisar antes estar emulando a loja do diretório "real" dela em /store.

2024-07-04 22:15 UTC, leomp12 commented
E o source dos testes por sua vez naturalmente devem estar dentro do respectivo pacote, porque ele tem relação com esse codebase e se esse codebase morre ele também morre.
Mas naturalmente onde está o source dos testes não define onde os testes serão executados.

2024-07-04 22:33 UTC, wisley7l commented
Ah sim, tinha entendido que os testes tinha que ser executados "diretamente" no dir da loja. haha
Ficou mais claro agora, então os outros testes criados até então estão de acordo, tinha achado que estavam todos errados :frowning:

2024-07-04 22:36 UTC, leomp12 commented
Os outros testes até agora nem entram nessa discussão porque são testes
unitários, ou quase, certamente não são e2e, não dependem de outros pacotes
exceto o seu respectivo.

Em qui., 4 de jul. de 2024, 19:34, Wisley Alves ***@***.***>
escreveu:

> Ah sim, tinha entendido que os testes tinha que ser executados
> "diretamente" no dir da loja. haha
> Ficou mais claro agora, então os outros testes criados até então estão de
> acordo, tinha achado que estavam todos errados 😦
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ecomplus/cloud-commerce/pull/406#issuecomment-2209615285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOZELDHCXRFXKQMRYZFVT3ZKXEV5AVCNFSM6AAAAABKCNFSQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMBZGYYTKMRYGU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-07-04 22:38 UTC, leomp12 commented
Quer dizer, não dependem da execução de uma ação (como criar um pedido ou
simular um PubSub) que não tá no seu próprio codebase.

Em qui., 4 de jul. de 2024, 19:36, Leonardo Matos ***@***.***>
escreveu:

> Os outros testes até agora nem entram nessa discussão porque são testes
> unitários, ou quase, certamente não são e2e, não dependem de outros pacotes
> exceto o seu respectivo.
>
> Em qui., 4 de jul. de 2024, 19:34, Wisley Alves ***@***.***>
> escreveu:
>
>> Ah sim, tinha entendido que os testes tinha que ser executados
>> "diretamente" no dir da loja. haha
>> Ficou mais claro agora, então os outros testes criados até então estão de
>> acordo, tinha achado que estavam todos errados 😦
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ecomplus/cloud-commerce/pull/406#issuecomment-2209615285>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ACOZELDHCXRFXKQMRYZFVT3ZKXEV5AVCNFSM6AAAAABKCNFSQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMBZGYYTKMRYGU>
>> .
>> You are receiving this because your review was requested.Message ID:
>> ***@***.***>
>>
>

2024-07-04 22:40 UTC, leomp12 commented
Pros testes e2e, como o que você propôs do e-mail, a loja deve ser emulada
"por inteiro", para tanto no seu próprio diretório (/store), o server que
será consumido pros testes estará rodando ali, mas os scripts dos testes
devem estar cada um em seu respectivo codebase, e não deve fazer nada além
de executar os respectivos testes mesmo (sem copiar pastas, tentar emular a
loja).

Em qui., 4 de jul. de 2024, 19:37, Leonardo Matos ***@***.***>
escreveu:

> Quer dizer, não dependem da execução de uma ação (como criar um pedido ou
> simular um PubSub) que não tá no seu próprio codebase.
>
> Em qui., 4 de jul. de 2024, 19:36, Leonardo Matos ***@***.***>
> escreveu:
>
>> Os outros testes até agora nem entram nessa discussão porque são testes
>> unitários, ou quase, certamente não são e2e, não dependem de outros pacotes
>> exceto o seu respectivo.
>>
>> Em qui., 4 de jul. de 2024, 19:34, Wisley Alves ***@***.***>
>> escreveu:
>>
>>> Ah sim, tinha entendido que os testes tinha que ser executados
>>> "diretamente" no dir da loja. haha
>>> Ficou mais claro agora, então os outros testes criados até então estão
>>> de acordo, tinha achado que estavam todos errados 😦
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/ecomplus/cloud-commerce/pull/406#issuecomment-2209615285>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/ACOZELDHCXRFXKQMRYZFVT3ZKXEV5AVCNFSM6AAAAABKCNFSQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMBZGYYTKMRYGU>
>>> .
>>> You are receiving this because your review was requested.Message ID:
>>> ***@***.***>
>>>
>>

2024-08-01 17:27 UTC, closed without merging