[WIP] feat(cloudCommerce-emails): Create emails package
ecomplus/cloud-commerce pull request #68
Opened 2022-10-27 18:19 UTC by wisley7l

2022-10-28 18:51 UTC, leomp12 reviewed
Dá uma olhada nisso aqui de referência https://docs.adonisjs.com/guides/mailer

2022-10-28 18:51 UTC, leomp12 commented on packages/config/src/env.ts
> +    providerMailId?: string,
_provider mail id_ não faz sentido 😛 :
https://translate.google.com/?sl=en&tl=pt&text=provider%20mail%20id&op=translate

```suggestion
    emailProviderId?: string,
```

Ou (como já está no objeto `emailProvider`):

```suggestion
    providerId?: string,
```

2022-10-28 18:51 UTC, leomp12 commented on packages/config/src/env.ts
> +  emailProvider: {
```suggestion
  mailer: {
```

😬 🤔

2022-10-28 18:59 UTC, leomp12 commented on packages/config/src/env.ts
> +  }
No no

2022-10-28 19:12 UTC, leomp12 commented on packages/emails/src/index.ts
> +  template?: {[x:string]: any},
É só uma string uai

2022-10-28 19:28 UTC, leomp12 commented
📲

`MAIL_SENDER`
`MAIL_SENDER_NAME`
`MAIL_REPLY_TO`

---

`SMTP_HOST`
`SMTP_POST`
`SMTP_USER`
`SMTP_PASS`

---

`SENDGRID_API_KEY`

2022-10-28 19:34 UTC, leomp12 commented
se `templateId` & `SENDGRID_API_KEY` => envia pela API do SendGrid usando o respectivo template
se não, se `SENDGRID_API_KEY` => faz o parse do template padrão e envia pela API do SendGrid
se não, se `SMTP_*` => faz o parse do template padrão e envia por SMTP
se não => não envia

2022-10-28 19:35 UTC, leomp12 commented
SendGrid pode ser substituído no futuro com outras opções de provides, `MAILGUN_API_KEY` por exemplo

2022-11-02 04:04 UTC, leomp12 commented on packages/emails/src/types/index.d.ts
> +  email: string
E na verdade isso aí tá no objeto `customer` né...

2022-11-02 04:04 UTC, leomp12 commented on packages/emails/src/index.ts
> +  const { templateData, templateId, template } = templateConfig;
```ts
emails.paid({ order, customer })
```

2022-11-02 04:04 UTC, leomp12 commented on packages/emails/src/index.ts
> +  const { templateData, templateId, template } = templateConfig;
Até o `customer` poderia ser opcional, você consegue pegar ele pelo objeto do `order`/`cart`

2022-11-02 04:04 UTC, leomp12 commented on packages/emails/src/index.ts
> +  const { templateData, templateId, template } = templateConfig;
Mas o principal é abstrair e reutilizar pelo menos o `store`/`lang`/`customMessage` (aliás esse útlimo seria configurado onde a partir de agora ? 🤔 )

2022-11-02 04:27 UTC, leomp12 commented on packages/emails/src/index.ts
> +  const { templateData, templateId, template } = templateConfig;
Sobre o `store`, falamos sobre algumas informações da loja que ficam no [`content/settings.json`](https://github.com/ecomplus/store/blob/7fac578f468ce134b0bc5cbba7b0accd146d401a/functions/ssr/content/settings.json) e poderiam/deveriam ser reutilizadas além do storefront, por exemplo nos e-mails.
Eu acho que os fields do settings já são suficientes pro que é usado no data do e-mail, sendo esse realmente o caso evitamos ter que consumir a API e também fica mais congruente com o próprio deploy (a mesma loja pode ter mais de um deploy com diferentes cores, domínios...), mas não acho que vamos tirar isso do `content/settings.json` porque a intenção é que venha do CMS, não precise ser configurado via env, aí estive pensando no pacote `@cloudcommerce/emails` (e outros que precisem) importar o `content/settings.json`, ele fica fora do codebase da respectiva Cloud Function então talvez seja necessário copiar o arquivo pra lá (talvez em todas) no build do `@cloudcommerce/cli`.
Sacou? 😬

2022-11-02 23:47 UTC, leomp12 commented
> Supondo que a gente vá enviar o e-mail de novo pedido em dois lugares diferentes, uma retentativa ou talvez dois apps, os dois terão que "adivinhar" o templateData correto pra esse e-mail e enviar na chamada da função.
Fora isso, se algo mudar no template padrão (via @ecomplus/transactional-mails) os dois lugares que disparam o e-mail terão que ser alterados.

OU na verdade o `@cloudcommerce/emails` não deva importar `@ecomplus/transactional-mails` diretamente, aí sim ele recebe o data (sem saber o que é) e o template (markup ou ID), nesse caso teríamos um app pra e-mails transacionais (o https://github.com/ecomplus/app-ses atual) que importaria o `@ecomplus/transactional-mails` para os templates padrão e poderia ser configurado com a `customMessage` ou o template ID pra cada tipo de e-mail.

A diferença é que esse app agora não vai diretamente ter uma função pra disparar o e-mail com SDK de algum serviço (sem o https://github.com/ecomplus/app-ses/blob/master/lib/send-mails.js nesse caso),  em vez disso ele usaria o método exportado pelo `@cloudcommerce/emails`. Também não precisaremos mais de um app de e-mails transacionais pra cada serviço de e-mail.

```ts
import sendEmail from `@cloudcommerce/emails`;

// Mesmas opções do nodemailer mas sem o `to` e `replyTo` (por env o `@cloudcommerce/emails` já vai ter eles):
await sendEmail({
  to: "bar@example.com, baz@example.com", // list of receivers
  subject: "Hello ✔", // Subject line
  text: "Hello world?", // plain text body
  html: "<b>Hello world?</b>", // html body
});

// OU com template markup (EJS, talvez MJML depois):
await sendEmail({
  to: "bar@example.com, baz@example.com", // list of receivers
  subject: "Hello ✔", // Subject line
  template: '<b><%= abc %></b>',
  templateData: { abc: 'Hello world?' },
});

// OU com template ID:
await sendEmail({
  to: "bar@example.com, baz@example.com", // list of receivers
  subject: "Hello ✔", // Subject line
  templateId: '123456789',
  templateData: { abc: 'Hello world?' },
});
// Isso deve dar erro se não tiver a chave do SendGrid configurada porque você não conseguiria enviar o e-mail por template ID
```

https://nodemailer.com/message/ 👀 

O que acha?

2022-11-03 19:41 UTC, wisley7l commented
Confesso que a principio estava imaginado assim, mas na nossa última **_Call_** que mudei para essa abordagem implementada com o _@ecomplus/transacional-emails_

2022-11-04 20:26 UTC, wisley7l commented on packages/emails/src/types/index.d.ts
> +  email: string
na verdade, acho q não, o objeto de emails do `customer` é um pouco diferente.

2022-11-04 21:14 UTC, wisley7l commented
@leomp12 algumas dúvidas aqui. 
* A  variável  `MAIL_SENDER_NAME` poderia vir do `content/settings.json`? se sim, fiquei com dúvida em como aproveitar aqui nesse pacote. 

* As variaveis mencionadas aqui https://github.com/ecomplus/cloud-commerce/pull/68#issuecomment-1295374687, deverão estar presente no arquivo `action.yml` como inputs ? semelhante ao input do `TINY_ERP_TOKEN`? 

*  o App Avise-me deverá tem um campo para inserir `TemplateId`, com a finalidade do lojista cadastrar o id dos respectivos templates criados no SendGrid e/ou futuramente outro app? 

> nesse caso teríamos um app pra e-mails transacionais (o https://github.com/ecomplus/app-ses atual) que importaria o @ecomplus/transactional-mails para os templates padrão e poderia ser configurado com a customMessage ou o template ID pra cada tipo de e-mail.

* E o app de emails transacionais aqui como mencionado, aqui para CloudCommerce seria uma junção do do app do SendGrid com o SES? onde que no momento para disparar o email ele ira passar todos os parametros que definimos aqui no `@cloudcommerce/emails` ?

2022-11-05 02:05 UTC, leomp12 commented on packages/emails/src/types/index.d.ts
> +  email: string
É diferente mas a informação tá lá 😄

2022-11-05 02:07 UTC, leomp12 commented on packages/emails/src/types/index.d.ts
> +  email: string
O que eu quis dizer foi isso, você já tem o nome e o e-mail no objeto `customer`, considerando que você já estava usando os templates do transactional mails dieratemtne você sabe que teria o objeto `customer` no template data, então pedir o e-mail e nome nesse objeto header de novo seria desnecessário. Você iria pedir a mesma informação duas vezes

2022-11-05 02:19 UTC, leomp12 commented
> A variável MAIL_SENDER_NAME poderia vir do content/settings.json? se sim, fiquei com dúvida em como aproveitar aqui nesse pacote.

Testa a env primeiro, se ela não existir você pega o nome da loja por padrão, [`settings.name`](https://github.com/ecomplus/store/blob/5ee79af1d15cd4e4e6b2d6edf848936b5cc83b2d/functions/ssr/content/settings.json#L7).

> As variaveis mencionadas aqui https://github.com/ecomplus/cloud-commerce/pull/68#issuecomment-1295374687, deverão estar presente no arquivo action.yml como inputs ? semelhante ao input do TINY_ERP_TOKEN?

Sim 👍🏾 

> o App Avise-me deverá tem um campo para inserir TemplateId, com a finalidade do lojista cadastrar o id dos respectivos templates criados no SendGrid e/ou futuramente outro app?

Idealmente sim 👍🏾
Mas tem que ter um template de e-mail padrão também.

> E o app de emails transacionais aqui como mencionado, aqui para CloudCommerce seria uma junção do do app do SendGrid com o SES? onde que no momento para disparar o email ele ira passar todos os parametros que definimos aqui no @cloudcommerce/emails ?

Não sei se uma junção 🙃 
Eu acho que ele é praticamente o app SES atual, só que em vez de usar o SDK da AWS ele dispara os e-mails usando o `@cloudcommerce/emails`, faz sentido? Além disso ele passa a ter uma opção de configuração a mais pro template ID em cada tipo de e-mail (assim como tem mensagem customizada em cada um), esse template ID não necessariamente vai ser do SendGrid (por enquanto é porque só integramos ele).

2022-11-05 02:23 UTC, leomp12 commented
> Confesso que a principio estava imaginado assim, mas na nossa última Call que mudei para essa abordagem implementada com o @ecomplus/transacional-emails

Saquei, é que você perguntou de onde vem os templates e vem do `@ecomplus/transacional-emails` por padrão, mas quem usa o transactional mails é o app de e-mails transacionais (antigo SES e SendGrid, mas que agora vai ser um único em vez de um por provedor).

> Tanto que a principio tinha imaginado o template como um objeto: até para que fosse possível passar uma propriedade type no template para que identificar se era um ejs ou outro tipo de template, mas sendo ejs o type default.

Bom também, mas aceite ele como objeto ou string, se for string é EJS.

2022-11-08 02:35 UTC, leomp12 reviewed
![hoje-nao-hoje-sim](https://user-images.githubusercontent.com/10326572/200461075-d8230bdd-73a2-40d8-a222-1e3729ab2526.gif)

2022-11-08 02:35 UTC, leomp12 commented on action.yml
> +    description: "Emails: Reply email"
Tava faltando o `main-sender-name`, o resto é texto...

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/tsconfig.json
> +}
```suggestion
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "declaration": true
  }
}

```

Esse pacote precisa declarar tipos...

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/providers/sendgrid/parse-to-data.ts
> +  logger.log('>> from: ', emailHeaders.from.email, ' to: ', JSON.stringify(emailHeaders.to));
Vários apps podem usar a lib, então evite que a lib faça mais do que ela é destinada a fazer (só mandar o e-mail), e se for fazer algo a mais se lembre de que isso é uma lib e pode estar em diferentes contextos, quer dizer, podemos ter um app de CRM que faz mil coisas e por acaso em algum momento dispara um e-mail, aparecer esse log aí no meio da execução dele sem muita explicação não parece ter utilidade, nem vamos saber do que se trata...

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/providers/sendgrid/parse-to-data.ts
> +  logger.log('>> from: ', emailHeaders.from.email, ' to: ', JSON.stringify(emailHeaders.to));
```suggestion
```

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/providers/sendgrid/parse-to-data.ts
> +  logger.log('>> from: ', emailHeaders.from.email, ' to: ', JSON.stringify(emailHeaders.to));
```suggestion
```

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/providers/sendgrid/parse-to-data.ts
> +) => {
```suggestion
const createBodySendGrid = (headersEmail: EmailHeaders) => {
```

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/providers/sendgrid/index.ts
> +    return { status: status || 400, message };
Uai pq isso aqui retorna status e message?

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/parse-template-to.html.ts
> +  }
Nem a pau juvenal 😛

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/parse-template-to.html.ts
> +  }
Então o app nunca vai saber que o envio falhou, ou pelo menos não sabe pq falhou? O dev tem que ver em log o erro que tá com stack trace na lib e não no app que consome a lib?

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/parse-template-to.html.ts
> +  }
A lib tem que dar throw quando o usuário envia algo errado...

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/index.ts
> +  return { status: 404, message: 'Provider settings or smtp not found' };
Não faz sentido nenhum usarmos erros HTTP aqui 🙃

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/index.ts
> +  return { status: 404, message: 'Provider settings or smtp not found' };
O código no app deve ser algo como:

```ts
try {
  await sendEmail()
} catch (err) {
  // retry ? ignore ? crash ?
}
```

O código que consome a lib é que decide o que faz se houve um erro, ideal é que você tenha códigos pra erros comuns inclusive (parâmetro faltando, template inválido...).

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/index.ts
> +  return { status: 404, message: 'Provider settings or smtp not found' };
Sem dar throw em erros o código teria que ser, no mínimo:

```ts
try {
  const { status } = await sendEmail()
  if (status !== 200) {
    throw new Error('Cannot send this e-mail')
  }
} catch (err) {
  // retry ? ignore ? crash ?
}
```

Só dificultou as coisas.

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/index.ts
> +  return { status: 404, message: 'Provider settings or smtp not found' };
E ainda dificulta pra você, porque dessa forma você tem que parsear erros do nodemailer, quando você poderia simplesmente deixar o throw

2022-11-08 02:35 UTC, leomp12 commented on packages/emails/src/index.ts
> +  return { status: 404, message: 'Provider settings or smtp not found' };
Lembre-se de que aqui você está implementando uma lib que exporta um método, não uma aplicação final ou endpoint HTTP...

2022-11-08 02:41 UTC, leomp12 commented on packages/emails/src/index.ts
> +  return { status: 404, message: 'Provider settings or smtp not found' };
⚠️ Travei a PR (de novo, foi mal 🙃 ) por causa desses retornos aí de null ou `{ status, message }` em erro, o restante que eu comentei passava, talvez eu só comitava aqui uma edição ou outra em texto e tal...
Com isso aqui não tem como passar: **um método reutilizável jogar erro em log e retornar null jamais, da mesma forma um método reutilizável com zero relação direta com uma API HTTP retornar erros em padrão REST em vez de instâncias de erro da própria linguagem (e throws), jamais também** 😬 💟

2022-11-08 02:44 UTC, leomp12 commented
⚠️ Travei a PR (de novo, foi mal 🙃 ) por causa desses retornos aí de null ou `{ status, message }` em erro, o restante que eu comentei passava, talvez eu só comitava aqui uma edição ou outra em texto e tal e já ia dar merge...

Maaaas:
- método reutilizável jogar erro em log e retornar null = **jamais**
- método reutilizável com zero relação direta com uma API HTTP retornar erros em padrão REST em vez de instâncias de erro da própria linguagem (e throws) = **jamais, jamé, never, nunca** 😬 💟

2022-11-08 02:45 UTC, leomp12 requested changes
⚠️ Travei a PR (de novo, foi mal 🙃 ) por causa desses retornos aí de null ou `{ status, message }` em erro, o restante que eu comentei passava, talvez eu só comitava aqui uma edição ou outra em texto e tal e já ia dar merge...

Maaaas:
- método reutilizável jogar erro em log e retornar null = **jamais**
- método reutilizável com zero relação direta com uma API HTTP retornar erros em padrão REST em vez de instâncias de erro da própria linguagem (e throws) = **jamais, jamé, never, nunca** 😬 💟

2022-11-08 17:29 UTC, wisley7l commented
> :warning: Travei a PR (de novo, foi mal :upside_down_face: ) 

kkk Ta errado tem que barrar msm. 
Fiz as correções e tentei fazer umas melhorias (espero q não tenha viajado/piorado) para configuração dos `providers` separado.

2022-11-09 02:42 UTC, leomp12 approved these changes
lgtm 🎆 😄 
bora ver rodando isso aí se vai de gg

2022-11-09 02:42 UTC, leomp12 commented on packages/emails/types/index.d.ts
> +}
Na verdade isso aqui não vai rolar pq não tem muito aplicabilidade e pra OAuth precisaria de um endpoint de callback e tal...

2022-11-09 02:44 UTC, merged