feat(send-transactional-emails): Create default app for sending transactional emails,
ecomplus/cloud-commerce pull request #73
Opened 2022-11-10 21:15 UTC by wisley7l

Substituir a PR#62 do app do sendGrid

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/package.json
> +  "name": "@cloudcommerce/app-send-transactional-emails",
```suggestion
  "name": "@cloudcommerce/app-emails",
```

🙃 

> Ou talvez `app-transactional-emails` (ainda acho que `app-emails` é melhor, simples e suficiente), esse `send-` aí que nem rola no nome do app

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/package.json
> +    "axios": "^1.1.3",
Não tá usando axios...

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/utils.ts
> +  };
Os apps recebem eventos agora por Pub/Sub, não webhooks, retornar `{ status: 500 }` pro Pub/Sub é inútil 🙃

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/utils.ts
> +  };
Se ainda fosse webhook, status code de erro na resposta geraria uma retentativa, como agora usamos Pub/Sub vai haver retentiva se a função falhar (throw error, olha nós de novo 😬 )

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/utils.ts
> +  };
Em geral (falando de forma mais simplista) esqueça isso de `return { status, error }`, isso só deve acontecer em funções de apps de módulos (calculate shipping, list payments...) porque nesse caso de fato é uma função HTTP e a resposta de erro é com especificações REST.
Fora isso, erro (erro mesmo, não alerta, info...) é `throw new Error(...)`.

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/handle-orders.ts
> +        return { status: 404, message: 'Not found Order or Store' };
Ixe 😄

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/handle-orders.ts
> +        return { status: 404, message: 'Not found Order or Store' };
Só pra constar, esse `return { status: 404 ... }` também é inútil aqui mas nesse caso não queremos um error throw porque não é uma falha da função, é uma "falha do cliente" (em REST 4xx é falha do cliente, isso aqui também não geraria uma retentativa do webhook)

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/handle-orders.ts
> +        return { status: 404, message: 'Not found Order or Store' };
Quer dizer, o payload do evento parece não ser válido, uma retentativa com ele não resolve o problema, só executaria várias (inifinitas ? 😬 ) vezes a função com o payload inválido

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/handle-orders.ts
> +        return { status: 404, message: 'Not found Order or Store' };
Isso aqui vira apenas um `logger.warn`

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/handle-orders.ts
> +        return { status: 404, message: 'Not found Order or Store' };
Tipo aí https://github.com/ecomplus/cloud-commerce/blob/main/packages/apps/tiny-erp/src/event-to-tiny.ts#L45

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/handle-orders.ts
> +        return { status: 404, message: 'Not found Order or Store' };
E nesse caso o que resta é torcer pro "cliente" ver o erro no log e corrigir o problema pros próximos eventos funcionarem corretamente

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/abandoned-carts.ts
> +      api.get('stores/me'),
Não acho que precisa dessa request em `stores/me`, mesma lógica do `@cloudcommerce/emails` (sem env nesse caso, só pelo `cmsSettings`)

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/abandoned-carts.ts
> +      api.get('stores/me'),
Talvez pra atender o modelo nos templates atuais você só tenha que renomear alguns fields:

```ts
const store = {
  domain: cmsSettings.domain,
  name: cmsSettings.name,
  contact_email: cmsSettings.email,
  logo: {
    url: `https://${cmsSettings.domain}${cmsSettings.logo}`,
  },
  // ...
}
```

A ver quais fields do `store` são usados nesses templates, pelo que vi seria só esses aí mesmo...

2022-11-11 05:35 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/abandoned-carts.ts
> +      api.get('stores/me'),
Isso na verdade não é só por performance, se a loja tiver dois deploys (duas línguas, talvez duas marcas...) o correto é pegar os dados do CMS do respectivo deploy, pelo menos o domínio certamente vai ser diferente de um deploy pra outro

2022-11-11 05:36 UTC, leomp12 requested changes
🙃

2022-11-11 05:37 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/abandoned-carts.ts
> +      api.get('stores/me'),
A propósito vai tem mais info no `cmsSettings` agora https://github.com/ecomplus/cloud-commerce/commit/25ceb8cfd7544bc4e7a6bd26437bb4ddadad3e2e

2022-11-12 22:54 UTC, leomp12 commented on packages/apps/emails/package.json
> +  "description": "E-Com Plus Cloud Commerce default transactional email sending app",
```suggestion
  "description": "E-Com Plus Cloud Commerce default transactional email app",
```

2022-11-12 22:54 UTC, leomp12 commented on packages/apps/send-transactional-emails/src/functios-lib/abandoned-carts.ts
> +      api.get('stores/me'),
Jogamos pro settings também..

2022-11-12 22:54 UTC, leomp12 commented on packages/apps/emails/src/functios-lib/utils.ts
> +    corporate_name: cmsSettings.name,
```suggestion
    corporate_name: cmsSettings.corporate_name || cmsSettings.name,
```

2022-11-12 22:54 UTC, leomp12 commented on packages/apps/emails/src/functios-lib/utils.ts
> +    address: '', // TODO: cmsSettings.address,
```suggestion
    address: cmsSettings.address,
```

Tá lá agora 👍🏾

2022-11-12 22:54 UTC, leomp12 commented on packages/firebase/src/config.ts
> +      appId: 1243, // appId of the SES app
```suggestion
      appId: 1243,
```

2022-11-12 22:54 UTC, leomp12 commented on packages/apps/emails/src/events-to-app-emails.ts
> +  }
```suggestion
  return handleOrder(apiEvent, app, apiDoc as Orders);
```

Vai chegar só eventos de pedidos porque:

```ts
const emailsEvents: ApiEventName[] = [
  'orders-new',
  'orders-anyStatusSet',
];
```

2022-11-12 22:54 UTC, leomp12 commented on packages/apps/emails/src/functios-lib/utils.ts
> -};
Onde tava usando essa função antes, não achei 🤔 
Onde ela estava deve haver um error throw, você sacou né?

2022-11-12 23:01 UTC, leomp12 commented on packages/apps/emails/src/firebase.ts
> +    memory: '128MB',
```suggestion
    memory: '256MB',
```

128 é só pra função que checa eventos mesmo, executa a cada minuto e é mais simples também, aqui é possível que 128 seja pouco demais e dê BO 🙃

2022-11-12 23:03 UTC, leomp12 commented on packages/apps/emails/src/firebase.ts
> +export const sendgrid = {
```suggestion
export const emails = {
```

2022-11-12 23:03 UTC, leomp12 commented on packages/apps/emails/src/firebase.ts
> +    .schedule('25 */3 * * *')
Idealmente isso aqui deveria ser configurável também, pensamos nisso no futuro

2022-11-14 19:41 UTC, wisley7l commented on packages/apps/emails/src/functios-lib/utils.ts
> -};
Era um try/catch que esta usando essa função. 
Tinha esquecido de excluir ela no commit anterior.

2022-11-15 00:44 UTC, leomp12 commented on packages/apps/emails/src/firebase.ts
> +    timeoutSeconds: 300,
Na verdade não precisa dos 5 min de timeout também, comi mosca aqui 🙃 
Acho que nem gasta esse `runWith` aqui nada, só deixar os padrões do Firebase Functions mesmo (256mb e 1min)

2022-11-15 00:44 UTC, leomp12 commented on packages/apps/emails/src/firebase.ts
> +  sendAbandonedCartsEmail: functionBuilder.pubsub
```suggestion

export const emails = {
  onStoreEvent: createAppEventsFunction(
    'emails',
    handleApiEvent as ApiEventHandler,
  ),

  cronAbandonedCarts: functions.region(region).pubsub
```

2022-11-15 00:46 UTC, leomp12 approved these changes
valeu nelson @wisley7l ⭐

2022-11-15 00:47 UTC, merged