[WIP] feat(pagar-me): Create app pagar.me
ecomplus/cloud-commerce pull request #78
Opened 2022-11-16 20:04 UTC by wisley7l

2022-11-16 20:05 UTC, wisley7l commented
Ainda não houve nenhum teste

2022-11-17 01:45 UTC, leomp12 requested changes
Não entendi se ainda tava mexedo aqui ou não 😛 

> Ainda não houve nenhum teste

Teste unitário você diz? Por enquanto vai sem mesmo, teste de app acho que só faz sentido sento e2e na verdade, aí tem toda uma stack pra levantar pra isso ainda 🙃

2022-11-17 01:45 UTC, leomp12 commented on packages/apps/pagarme/tsconfig.json
> +}
```suggestion
{
  "extends": "../../../tsconfig.json",
  "compilerOptions": {
    "declaration": true
  }
}
```

App com módulos exporta uma função chamada em código, então é bom ter type declarations...

2022-11-17 01:45 UTC, leomp12 commented on packages/apps/pagarme/src/pagarme-create-transaction.ts
> +      return err;
`.catch(err => { return err })` não propaga, isso aqui se perde, nesse trecho o erro não seria tratado de nenhuma forma na verdade

2022-11-17 01:45 UTC, leomp12 commented on packages/apps/pagarme/src/pagarme-create-transaction.ts
> +  axios({
Não deveria ser um `return axios ... `?

2022-11-17 01:45 UTC, leomp12 commented on packages/apps/pagarme/src/pagarme-create-transaction.ts
> +  axios({
Precisa retornar a promise pro módulo, quando chama a função, saber se ela foi completada ou não

2022-11-17 01:45 UTC, leomp12 commented on packages/apps/pagarme/src/pagarme-create-transaction.ts
> +  axios({
Ou então converte pra `async / await` como no do MP, Correios, Frenet ...

2022-11-18 16:25 UTC, leomp12 approved these changes
Valeu 👍🏾 💯

2022-11-18 16:25 UTC, merged