feat/app infinitepay
ecomplus/cloud-commerce pull request #83
Opened 2022-11-23 17:33 UTC by wisley7l

2022-11-27 16:34 UTC, leomp12 requested changes
Coé @wisley7l ,
A maioria aí são minors, mas acho que vale a pena dar uma melhorada em alguns comentários, em especial no erro sobre headers sent no webhook deles e as parcelas que não sei porque estão em JSON (talvez se você usasse client side tbm, mas não é o caso pelo que vi...) 🙃

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-webhook.ts
> +const handleErro = (error: any, res: Response, status?: number) => {
Misturar inglês com português dá uma dorzinha na alma 😬

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-create-transaction.ts
> +      last_name: buyer.fullname.split(' ')[buyer.fullname.split(' ').length - 1],
3x `buyer.fullname.split(' ')` 😐

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-list-payments.ts
> +        gateway.icon = 'https://us-central1-ecom-pix.cloudfunctions.net/app/pix.png';
Isso é o ícone pro marketplace de apps do app do Pix né?
Acho que tá assim inclusive no https://github.com/ecomplus/app-infinitepay atual, certo? Não é uma boa não, o ícone pro marketplace é um 600x600 que aparece no admin, esse `gateway.icon` na verdade é pra aparecer na lista de pagamento e em geral é uma imagem bem mais retangular, esse ícone deve ficar meio ruim lá.

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/assets/ip-interest-monthly.json
> +[
Por que JSON aqui?
Por que não um módulo mesmo com `export default` normalmente? Mais fácil e mais rápido do que ter que ler arquivo JSON, parsear...

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-webhook.ts
> +  return res.sendStatus(403);
Vai dar erro aqui, se chegar nesse 404 depois também vai pra linha 182 e tenta enviar a resposta duas vezes

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-webhook.ts
> +  return res.sendStatus(403);
`headers already sent` ...

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-webhook.ts
> +      res.send({
```suggestion
      return res.send({
```
?

2022-11-27 16:34 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-list-payments.ts
> +import * as logger from 'firebase-functions/logger';
```suggestion
import logger from 'firebase-functions/logger';
```

A não ser que você tenha visto algo que eu não vi, `import *` não é necessário aqui...

2022-11-27 19:28 UTC, leomp12 reviewed
https://github.com/ecomplus/cloud-commerce/commit/60107afda5ec5e3766e2c2bfc7a9e582583e9e93

2022-11-27 19:28 UTC, leomp12 commented on packages/apps/infinitepay/src/functions-lib/ip-auth/create-access.ts
> +const firestoreColl = 'infinitepay_tokens';
```suggestion
const firestoreColl = 'infinitepayTokens';
```

2022-11-27 19:28 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-webhook.ts
> +  const firestoreColl = 'infinitepay_transactions_pix';
```suggestion
  const firestoreColl = 'infinitepayTransactions';
```

2022-11-27 20:11 UTC, wisley7l commented on packages/apps/infinitepay/src/ip-list-payments.ts
> +import * as logger from 'firebase-functions/logger';
Meu Lint tava acusando erro, confesso que não entendi 🤦‍♂️

2022-11-27 20:19 UTC, wisley7l commented on packages/apps/infinitepay/src/ip-list-payments.ts
> +        gateway.icon = 'https://us-central1-ecom-pix.cloudfunctions.net/app/pix.png';
Mas esse é o icone para lista de pagamentos do app do PIX, se não me ganho usei como referencia isso o app do pagarme.

2022-11-30 22:05 UTC, leomp12 commented on packages/apps/infinitepay/src/ip-list-payments.ts
> +        gateway.icon = 'https://us-central1-ecom-pix.cloudfunctions.net/app/pix.png';
Ah sim..

2022-11-30 22:07 UTC, leomp12 approved these changes
boa nelson 👍🏾

2022-11-30 22:12 UTC, merged